export const PALETTES = {
    neon: [320, 290, 250, 200, 170, 120],
    sunset: [8, 18, 30, 42, 56, 70],
    ocean: [185, 198, 210, 224, 236, 248],
    forest: [68, 92, 116, 132, 150, 168],
    candy: [345, 320, 292, 265, 230, 200],
};
export const PRESETS = [
    {
        id: 'lissajous-ribbon',
        name: 'Lissajous Ribbon',
        exprX: 'R * sin(3 * t + PI / 2)',
        exprY: 'r * sin(2 * t)',
        exprZ: 'd * sin(5 * t + PI / 4)',
        generatorKind: 'lissajous',
        lissajousAx: 8,
        lissajousAy: 6,
        lissajousAz: 5.5,
        lissajousFx: 3,
        lissajousFy: 2,
        lissajousFz: 5,
        lissajousPhaseX: 1.5707963268,
        lissajousPhaseY: 0,
        lissajousPhaseZ: 0.7853981634,
        lissajousUMixX: 0.25,
        lissajousUMixY: 0.2,
        lissajousUMixZ: 0.3,
        R: 8,
        r: 6,
        d: 5.5,
        speed: 1.4,
        uSpeed: 0.5,
        lineLifetime: 10,
        pointSize: 2.2,
    },
    {
        id: 'strange-attractor-lorenz',
        name: 'Strange Attractor (Lorenz)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'lorenz',
        attractorSigma: 10,
        attractorRho: 28,
        attractorBeta: 2.6666666667,
        attractorStepScale: 1,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 0.35,
        attractorWarmupSteps: 120,
        R: 12,
        r: 12,
        d: 12,
        speed: 1.2,
        uSpeed: 0.2,
        lineLifetime: 12,
        pointSize: 1.8,
    },
    {
        id: 'strange-attractor-rossler',
        name: 'Strange Attractor (Rossler)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'rossler',
        attractorSigma: 0.2,
        attractorRho: 5.7,
        attractorBeta: 0.2,
        attractorStepScale: 1.4,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 3.2,
        attractorWarmupSteps: 180,
        R: 8,
        r: 8,
        d: 8,
        speed: 1.3,
        uSpeed: 0.25,
        lineLifetime: 14,
        pointSize: 1.7,
    },
    {
        id: 'strange-attractor-chen',
        name: 'Strange Attractor (Chen)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'chen',
        attractorSigma: 35,
        attractorRho: 28,
        attractorBeta: 3,
        attractorStepScale: 0.8,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 0.28,
        attractorWarmupSteps: 140,
        R: 11,
        r: 11,
        d: 11,
        speed: 1.1,
        uSpeed: 0.18,
        lineLifetime: 13,
        pointSize: 1.9,
    },
    {
        id: 'strange-attractor-thomas',
        name: 'Strange Attractor (Thomas)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'thomas',
        attractorSigma: 2.6,
        attractorRho: 28,
        attractorBeta: 2.08,
        attractorStepScale: 1.2,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 6,
        attractorWarmupSteps: 220,
        R: 10,
        r: 10,
        d: 10,
        speed: 1.2,
        uSpeed: 0.2,
        lineLifetime: 14,
        pointSize: 1.7,
    },
    {
        id: 'strange-attractor-halvorsen',
        name: 'Strange Attractor (Halvorsen)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'halvorsen',
        attractorSigma: 14,
        attractorRho: 28,
        attractorBeta: 2.4,
        attractorStepScale: 0.85,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 0.6,
        attractorWarmupSteps: 180,
        R: 12,
        r: 12,
        d: 12,
        speed: 1.05,
        uSpeed: 0.2,
        lineLifetime: 13,
        pointSize: 1.8,
    },
    {
        id: 'strange-attractor-aizawa',
        name: 'Strange Attractor (Aizawa)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'aizawa',
        attractorSigma: 10,
        attractorRho: 24,
        attractorBeta: 2.2,
        attractorStepScale: 0.9,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 1.5,
        attractorWarmupSteps: 180,
        R: 10,
        r: 10,
        d: 10,
        speed: 1.15,
        uSpeed: 0.22,
        lineLifetime: 14,
        pointSize: 1.8,
    },
    {
        id: 'strange-attractor-lu-chen',
        name: 'Strange Attractor (Lu-Chen)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'lu-chen',
        attractorSigma: 36,
        attractorRho: 20,
        attractorBeta: 3,
        attractorStepScale: 0.9,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 0.35,
        attractorWarmupSteps: 140,
        R: 11,
        r: 11,
        d: 11,
        speed: 1.05,
        uSpeed: 0.2,
        lineLifetime: 13,
        pointSize: 1.9,
    },
    {
        id: 'strange-attractor-rf',
        name: 'Strange Attractor (Rabinovich-Fabrikant)',
        exprX: 'x',
        exprY: 'y',
        exprZ: 'z',
        generatorKind: 'strange-attractor',
        attractorEquation: 'rabinovich-fabrikant',
        attractorSigma: 10,
        attractorRho: 14,
        attractorBeta: 1,
        attractorStepScale: 0.55,
        attractorInitialX: 0.1,
        attractorInitialY: 0,
        attractorInitialZ: 0,
        attractorScale: 0.9,
        attractorWarmupSteps: 220,
        R: 11,
        r: 11,
        d: 11,
        speed: 0.95,
        uSpeed: 0.2,
        lineLifetime: 14,
        pointSize: 1.8,
    },
    { id: 'classic-bloom', name: 'Classic Bloom', exprX: '(R - r) * cos(t + 0.25 * sin(u)) + d * cos(((R - r) / r) * t + 0.3 * cos(u))', exprY: '(R - r) * sin(t + 0.25 * sin(u)) - d * sin(((R - r) / r) * t + 0.3 * cos(u))', exprZ: '0.56 * ((R - r) * sin(t + 0.25 * sin(u)) + d * sin(((R - r) / r) * t + 0.3 * cos(u)))', R: 8, r: 3, d: 6, speed: 1.8, uSpeed: 0.45, lineLifetime: 8, pointSize: 2.4 },
    { id: 'lotus-wheel', name: 'Lotus Wheel', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.56 * ((R - r) * sin(t + 0.25 * sin(u)) + d * sin(((R - r) / r) * t + 0.2 * cos(u)))', R: 9.4, r: 4.2, d: 7.2, speed: 1.3, lineLifetime: 10, pointSize: 2.2 },
    { id: 'neon-knot', name: 'Neon Knot', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.58 * ((R - r) * cos(t + 0.3 * sin(u)) + d * cos(((R - r) / r) * t + u))', R: 10, r: 2.6, d: 8.4, speed: 2.2, lineLifetime: 7, pointSize: 1.6 },
    { id: 'orbital-petal', name: 'Orbital Petal', exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t)', exprZ: '0.56 * ((R + r) * sin(t + 0.3 * cos(u)) - d * sin(((R + r) / r) * t + 0.25 * sin(u)))', R: 4.6, r: 1.8, d: 4.2, speed: 2.5, lineLifetime: 6, pointSize: 1.8 },
    { id: 'tangled-star', name: 'Tangled Star', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) + d * sin(((R - r) / r) * t)', exprZ: '0.58 * ((R - r) * sin(t + 0.22 * sin(u)) - d * sin(((R - r) / r) * t - 0.25 * cos(u)))', R: 11, r: 3.7, d: 7, speed: 2.1, lineLifetime: 9, pointSize: 2 },
    { id: 'daisy-chain', name: 'Daisy Chain', exprX: '(R - r) * cos(t) + (d + 0.6 * sin(t * 0.5)) * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - (d + 0.6 * sin(t * 0.5)) * sin(((R - r) / r) * t)', exprZ: '0.54 * ((R - r) * sin(t + 0.2 * sin(u)) + (d + 0.6 * sin(t * 0.5)) * sin(((R - r) / r) * t + 0.2 * cos(u)))', R: 8.8, r: 3.2, d: 5.4, speed: 1.7, lineLifetime: 11, pointSize: 2.2 },
    { id: 'firework-sparks', name: 'Firework Sparks', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.62 * ((R - r) * cos(t + 0.45 * sin(u)) + d * cos(((R - r) / r) * t + 0.5 * u))', R: 7.2, r: 1.9, d: 6.5, speed: 3.1, lineLifetime: 4.2, pointSize: 2.8 },
    { id: 'planet-glyph', name: 'Planet Glyph', exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t)', exprZ: '0.56 * ((R + r) * sin(t + 0.26 * sin(u)) - d * sin(((R + r) / r) * t + 0.32 * cos(u)))', R: 5.2, r: 2.1, d: 6.6, speed: 1.4, lineLifetime: 12, pointSize: 1.4 },
    { id: 'helix-rose', name: 'Helix Rose', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t + sin(u))', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t + sin(u))', exprZ: '0.6 * ((R - r) * sin(t + 0.45 * sin(u)) + d * sin(((R - r) / r) * t + 0.45 * cos(u)))', R: 10.2, r: 4.4, d: 7.6, speed: 1.1, uSpeed: 0.6, lineLifetime: 13, pointSize: 2.3 },
    { id: 'atomic-lace', name: 'Atomic Lace', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.56 * ((R - r) * sin(t + 0.14 * sin(u)) + d * sin(((R - r) / r) * t + 0.25 * cos(u)))', R: 12, r: 5.1, d: 8.3, speed: 0.95, lineLifetime: 14, pointSize: 2 },
    { id: 'candy-swirl', name: 'Candy Swirl', exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t)', exprZ: '0.58 * ((R + r) * cos(t + 0.33 * sin(u)) - d * cos(((R + r) / r) * t + 0.35 * sin(u)))', R: 4.4, r: 1.4, d: 3.6, speed: 2.7, lineLifetime: 6.5, pointSize: 1.9 },
    { id: 'wobble-loop', name: 'Wobble Loop', exprX: '(R - r) * cos(t) + (d + 1.1 * cos(t * 0.7)) * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - (d + 1.1 * cos(t * 0.7)) * sin(((R - r) / r) * t)', exprZ: '0.56 * ((R - r) * sin(t + 0.25 * cos(u)) + (d + 1.1 * cos(t * 0.7)) * sin(((R - r) / r) * t + 0.25 * sin(u)))', R: 9.8, r: 3.4, d: 6.2, speed: 1.6, lineLifetime: 9.5, pointSize: 1.3 },
    { id: 'radar-scan', name: 'Radar Scan', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.62 * ((R - r) * sin(t + 0.55 * saw(u)) + d * sin(((R - r) / r) * t + 0.45 * saw(u)))', R: 6.8, r: 2.2, d: 5.8, speed: 2.9, lineLifetime: 3.5, pointSize: 2.1 },
    { id: 'glass-petals', name: 'Glass Petals', exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t)', exprZ: '0.55 * ((R + r) * sin(t + 0.18 * sin(u)) - d * sin(((R + r) / r) * t + 0.28 * cos(u)))', R: 5.6, r: 2.5, d: 2.8, speed: 1.9, lineLifetime: 10.5, pointSize: 1.5 },
    { id: 'triad-bloom', name: 'Triad Bloom', exprX: '(R - r) * cos(t) + d * cos(3 * ((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(3 * ((R - r) / r) * t)', exprZ: '0.58 * ((R - r) * sin(t + 0.28 * sin(u)) + d * sin(3 * ((R - r) / r) * t + 0.35 * cos(u)))', R: 8.4, r: 3.1, d: 4.7, speed: 1.7, lineLifetime: 8.8, pointSize: 1.7 },
    { id: 'sunburst', name: 'Sunburst', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.64 * ((R - r) * cos(t + 0.5 * pulse(u, 0.2)) + d * cos(((R - r) / r) * t + 0.42 * pulse(u, 0.18)))', R: 11.4, r: 1.7, d: 9.2, speed: 3.3, lineLifetime: 4.8, pointSize: 3.3 },
    { id: 'moon-thread', name: 'Moon Thread', exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t)', exprZ: '0.56 * ((R + r) * sin(t - 0.3 * sin(u)) - d * sin(((R + r) / r) * t - 0.35 * cos(u)))', R: 3.9, r: 1.2, d: 5.1, speed: 2.2, lineLifetime: 7.5, pointSize: 1.9 },
    { id: 'echo-ring', name: 'Echo Ring', exprX: '(R - r) * cos(t) + (d * (0.75 + 0.25 * sin(t * 0.25))) * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - (d * (0.75 + 0.25 * sin(t * 0.25))) * sin(((R - r) / r) * t)', exprZ: '0.55 * ((R - r) * sin(t + 0.22 * triangle(u)) + (d * (0.75 + 0.25 * sin(t * 0.25))) * sin(((R - r) / r) * t + 0.3 * triangle(u)))', R: 9.1, r: 2.9, d: 6.9, speed: 1.5, lineLifetime: 11.2, pointSize: 2.1 },
    { id: 'threaded-comet', name: 'Threaded Comet', exprX: '(R - r) * cos(t) + d * cos(((R - r) / r) * t)', exprY: '(R - r) * sin(t) - d * sin(((R - r) / r) * t)', exprZ: '0.6 * ((R - r) * cos(t + 0.35 * sin(u)) + d * cos(((R - r) / r) * t * 0.85 + 0.4 * cos(u)))', R: 7.6, r: 2.4, d: 4.4, speed: 2.6, lineLifetime: 5.4, pointSize: 2.6 },
    { id: 'mandala-drift', name: 'Mandala Drift', exprX: '(R + r) * cos(t + 0.45 * sin(u)) - (d + 0.7 * sin(u * 0.8)) * cos(((R + r) / r) * t)', exprY: '(R + r) * sin(t + 0.45 * sin(u)) - (d + 0.7 * sin(u * 0.8)) * sin(((R + r) / r) * t)', exprZ: '0.56 * ((R + r) * sin(t + 0.45 * sin(u)) - (d + 0.7 * sin(u * 0.8)) * sin(((R + r) / r) * t + 0.3 * cos(u)))', R: 4.8, r: 1.6, d: 4.9, speed: 1.25, uSpeed: 0.35, lineLifetime: 12.5, pointSize: 1.6 },
];
export function createLayerFromPreset(preset, id, name) {
    return {
        id,
        name,
        visible: true,
        exprX: preset.exprX,
        exprY: preset.exprY,
        exprZ: preset.exprZ ?? '0',
        generatorKind: preset.generatorKind ?? 'parametric',
        lissajousAx: preset.lissajousAx ?? preset.R,
        lissajousAy: preset.lissajousAy ?? preset.r,
        lissajousAz: preset.lissajousAz ?? preset.d,
        lissajousFx: preset.lissajousFx ?? 3,
        lissajousFy: preset.lissajousFy ?? 2,
        lissajousFz: preset.lissajousFz ?? 5,
        lissajousPhaseX: preset.lissajousPhaseX ?? Math.PI / 2,
        lissajousPhaseY: preset.lissajousPhaseY ?? 0,
        lissajousPhaseZ: preset.lissajousPhaseZ ?? Math.PI / 4,
        lissajousUMixX: preset.lissajousUMixX ?? 0.25,
        lissajousUMixY: preset.lissajousUMixY ?? 0.2,
        lissajousUMixZ: preset.lissajousUMixZ ?? 0.3,
        attractorSigma: preset.attractorSigma ?? 10,
        attractorRho: preset.attractorRho ?? 28,
        attractorBeta: preset.attractorBeta ?? 8 / 3,
        attractorStepScale: preset.attractorStepScale ?? 1,
        attractorInitialX: preset.attractorInitialX ?? 0.1,
        attractorInitialY: preset.attractorInitialY ?? 0,
        attractorInitialZ: preset.attractorInitialZ ?? 0,
        attractorScale: preset.attractorScale ?? 0.35,
        attractorWarmupSteps: preset.attractorWarmupSteps ?? 120,
        attractorEquation: preset.attractorEquation ?? 'lorenz',
        R: preset.R,
        r: preset.r,
        d: preset.d,
        speed: preset.speed,
        uSpeed: preset.uSpeed ?? 0.4,
        lineLifetime: preset.lineLifetime,
        lineForever: true,
        pointSize: preset.pointSize,
        multiLineCount: 1,
        multiLineMotion: 'fixed',
        multiLineSpread: 14,
        multiLineMotionSpeed: 1,
        colorMode: 'hue-cycle',
        paletteId: 'neon',
        hueLock: false,
        baseHue: 210,
    };
}
export const EQUATION_EXAMPLES = [
    {
        id: 'drifted-hypotrochoid',
        name: 'Drifted Hypotrochoid',
        exprX: '(R - r) * cos(t + 0.3 * sin(u)) + d * cos(((R - r) / r) * t)',
        exprY: '(R - r) * sin(t + 0.3 * sin(u)) - d * sin(((R - r) / r) * t)',
        exprZ: '0',
    },
    {
        id: 'epitrochoid-wave',
        name: 'Epitrochoid Wave',
        exprX: '(R + r) * cos(t) - d * cos(((R + r) / r) * t + 0.5 * sin(u))',
        exprY: '(R + r) * sin(t) - d * sin(((R + r) / r) * t + 0.5 * sin(u))',
        exprZ: '0',
    },
    {
        id: 'pulse-rose',
        name: 'Pulse Rose',
        exprX: '(R - r) * cos(t) + (d * (0.6 + 0.4 * pulse(u, 0.2))) * cos(((R - r) / r) * t)',
        exprY: '(R - r) * sin(t) - (d * (0.6 + 0.4 * pulse(u, 0.2))) * sin(((R - r) / r) * t)',
        exprZ: '0',
    },
    {
        id: 'triangle-flower',
        name: 'Triangle Flower',
        exprX: '(R - r) * cos(t + triangle(u) * 0.7) + d * cos(((R - r) / r) * t)',
        exprY: '(R - r) * sin(t + triangle(u) * 0.7) - d * sin(((R - r) / r) * t)',
        exprZ: '0',
    },
    {
        id: 'saw-twist',
        name: 'Saw Twist',
        exprX: '(R - r) * cos(t) + (d + 1.2 * saw(u)) * cos(((R - r) / r) * t)',
        exprY: '(R - r) * sin(t) - (d + 1.2 * saw(u)) * sin(((R - r) / r) * t)',
        exprZ: '0',
    },
];
export const CUSTOM_PRESET_STORAGE_KEY = 'spiro2.custom-presets';
